version: '3.8'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./web:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
  php:
    image: php:fpm-alpine
    volumes:
      - ./web:/var/www/html
